:imagesdir: resources/images/

=== Reference API V1.0

==== citation-strings

**GET citation-strings** constructs the citation strings for this Reference using the rules in the 'ReferenceService' and
returns them as a JSON resource. This will not change the Reference object.

**PUT citation-strings**  constructs the citation strings for this Reference using the rules in the 'ReferenceService', updates
the Reference object with these strings, and returns them as a JSON resource.

Updating the citation strings of a Reference may be necessary if a citation string gets out of sync with the Reference data for
some reason, (such as an SQL update) or the citation construction algorithm has been changed.

This will re-write the HTML and plain citation on the Reference object.

NOTE: You need to be an administrator, or administrator service to call this with PUT. Use your apiKey to authenticate.

.Returns

 * The Brief Reference of the reference in the query
 * action: 'citation-strings'
 * result:
   - citationHtml: the full citation marked up with HTML5/XML
   - citation: the citation in plain text

.Example 1

curl -L -H "Accept: application/json" -X GET https://id.biodiversity.org.au/reference/apni/22536/api/citation-strings

.Response

[source, javascript]
----
{
  "class": "au.org.biodiversity.nsl.Reference",
  "_links": {
    "permalink": {
      "link": "https://id.biodiversity.org.au/reference/apni/22536",
      "resources": 1
    }
  },
  "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae",
  "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>",
  "action": "citation-strings",
  "result": {
    "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>",
    "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae"
  }
}
----

.Example 2

curl -L -H "Accept: application/json" -X PUT https://id.biodiversity.org.au/reference/apni/22536/api/citation-strings?apiKey=aaaaa-bbbbbb-eeee-ccccc-sssss

.Response

[source, javascript]
----
{
  "class": "au.org.biodiversity.nsl.Reference",
  "_links": {
    "permalink": {
      "link": "https://id.biodiversity.org.au/reference/apni/22536",
      "resources": 1
    }
  },
  "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae",
  "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>",
  "action": "citation-strings",
  "result": {
    "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>",
    "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae"
  }
}
----

==== delete

**GET delete** tells you if a reference can be deleted. If not it gives a list of error messages explaining why not.

**DELETE delete** deletes the reference if it can be deleted. If not it gives a list of error messages explaining why not.

NOTE: You need to be an administrator, or administrator service to call this with the 'DELETE' method.
Use your apiKey to authenticate.

.Returns

* Brief Reference object
* action: 'delete'
* ok: true/false - false means you can't delete this name
* errors: List - if ok is false this contains a list of error strings explaining the problem

if you are trying to delete and it fails (i.e. you didn't check if you could delete it) you will get a 403 return code,
with a payload containing error messages.

.Parameters
* reason - the reason this reference is being deleted.

.Example 1

Check if you can delete

curl -L -H "Accept: application/json" -X GET https://id.biodiversity.org.au/reference/apni/22536/api/delete.json

.response

[source, groovy]
----
{
  "reference": {
    "class": "au.org.biodiversity.nsl.Reference",
    "_links": {
      "permalink": {
        "link": "https://id.biodiversity.org.au/reference/apni/22536",
        "preferred": true,
        "resources": 1
      }
    },
    "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae",
    "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>"
  },
  "action": "delete",
  "ok": false,
  "errors": [
    "There are 2379 instances for this reference."
  ]
}
----

.Example 2

curl -L -H "Accept: application/json" -X DELETE https://id.biodiversity.org.au/reference/apni/22536/api/delete?apiKey=aaaaa-bbbbbb-ccccc-ddddd-eeeee&reason=I+dont+like+it

.Non working response

[source, groovy]
----
{
  "reference": {
    "class": "au.org.biodiversity.nsl.Reference",
    "_links": {
      "permalink": {
        "link": "https://id.biodiversity.org.au/reference/apni/22536",
        "preferred": true,
        "resources": 1
      }
    },
    "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae",
    "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>"
  },
  "action": "delete",
  "ok": false,
  "errors": [
    "There are 2379 instances for this reference."
  ]
}
----

.Working response

[source, groovy]
----
{
  "reference": {
    "class": "au.org.biodiversity.nsl.Reference",
    "_links": {
      "permalink": {
        "link": "https://id.biodiversity.org.au/reference/apni/22536",
        "preferred": true,
        "resources": 1
      }
    },
    "citation": "Brown, R. (1810), Prodromus Florae Novae Hollandiae",
    "citationHtml": "Brown, R. (1810), <i>Prodromus Florae Novae Hollandiae</i>"
  },
  "action": "delete",
  "ok": true
}
----

==== move

**DELETE move** move all associated resources for a reference to another reference. This is typically used in de-duplicating
references that have been entered multiple times. This action will:

* redirect the URI's associated with the source reference to the target reference,
* move all instances, comments, external references, notes, to the target reference, then
* delete the source reference.

WARNING: This will delete the source reference. You need to be an administrator to do this, so you will need an apiKey
if calling it from a service.

.Parameters

* target - the target reference id on the service, ie. the database ID (this is not intended for use externally)
* user - (optional) The user to blame, defaults to the administrator.

You use the resource URI as the **source** reference and pass the target reference ID as a parameter.

.example

curl -L -H "Accept: application/json" -X DELETE https://id.biodiversity.org.au/reference/apni/22536/api/move?target=22537&apiKey=blah_blah_blah?user=fred

.response

A brief target Reference object is returned along with the result "ok" to indicate success. If there are errors they
will be in an errors field as a list.

[source, javascript]
----
{
  "reference": {
    "class": "au.org.biodiversity.nsl.Reference",
    "_links": {
      "permalink": {
        "link": "https://id.biodiversity.org.au/reference/apni/30623",
        "preferred": true,
        "resources": 1
      }
    },
    "citation": "Stearn, W.T. in Stearn, W.T. (ed.) (1978), European species of Allium and allied genera of Alliaceae: a synonymic enumeration. Annales Musei Goulandris 4",
    "citationHtml": "Stearn, W.T. in Stearn, W.T. (ed.) (1978), European species of Allium and allied genera of Alliaceae: a synonymic enumeration. <i>Annales Musei Goulandris<\u002fi> 4"
  },
  "action": "move",
  "ok": true
}
----

==== deduplicate-marked

**DELETE deduplicate-marked** finds all references with duplicateOf set to another reference and calls the move action on it.

.Parameters

* user - (optional) The user to blame, defaults to the administrator.

WARNING: This will delete the duplicate references. You need to be an administrator to do this, so you will need an apiKey
if calling it from a service.

.example

curl -L -H "Accept: application/json" -X DELETE https://biodiversity.org.au/nsl/services/reference/api/deduplicate-marked?apiKey=blah_blah_blah?user=fred

.response

a list of de-duplicated reference DB IDs with an indication of success.

[source, javascript]
----
{
  "action": "deduplicate marked references",
  "count": 140,
  "references": [
    {
      "source": 30695,
      "target": 30623,
      "ok": true
    },
    {
      "source": 30693,
      "target": 30623,
      "ok": true
    },
    {
      "source": 50954,
      "target": 44601,
      "ok": true
    },
    {
      "source": 38140,
      "target": 25636,
      "ok": true
    },
    {
      "source": 29860,
      "target": 23959,
      "ok": true
    },
    {
      "source": 34172,
      "target": 25636,
      "ok": true
    },
    {
      "source": 34173,
      "target": 25636,
      "ok": true
    },
...
  ]
}
----